### ISSUE TITLE
Describe procedure used in Drews et al., 2022 for sWGS datasets

### ISSUE THREAD

**Issue by lbeltrame** [VanLoo-lab/ASCAT.sc#1]
I've filed [this issue](https://github.com/markowetzlab/Drews2022_CIN_Compendium/issues/1) on the official GH repo for the paper and I was suggested to post it here.

On page 34 of the Supplementary Methods, there is a reference to the sWGS copy number fitting method:

> "After the profile was segmented, we searched the space of combinations of realistic purity and ploidy values (0.01<purity<1,
1.5<average tissue ploidy<5, and tumour ploidy<5) to fit the logR to integer values, solving the logR equation for each segment:"

It is unclear if this part of the method is available anywhere. 

The reason for this question is that I want to apply the method described in the paper to an internal sWGS dataset. I already calculated purity- and ploidy-adjusted copy numbers for those samples, but I would like to see, when extracting signatures, if the method described in the paper, when applied to our data, performs better or worse than the one I used. Also, I relied on external data to do the calculations, while the estimates mentioned in the paper do not require additional, external input.

**Comment by galder-max** [comment]
Hi ibeltrame, 

Apologies for the late reply! Indeed, the fitting of purity/ploidy is done automatically internally by ASCAT.sc.
I am working on updated vignettes to make it as easy as possible for users to run the different modules of the package. But this is taking longer than expected. So in the meantime, please try and install the latest version and use the following code on your data:

```
####################################################################
library(ASCAT.sc)
####################################################################

####################################################################
## modify here
DIRECTORYWITHBAM  <- "../bams/" ## where your bams are, alternatively change object "bams"
PATHTOYOURFASTAFILE <- "genome.fa"
YOURWORKDIR <- "./" ## outputs here
## modify here
####################################################################

####################################################################
bams <- dir(DIRECTORYWITHBAM,
            pattern="bam$",full=T, rec=T)
fasta <- PATHTOYOURFASTAFILE
####################################################################

####################################################################
setwd(YOURWORKDIR)
####################################################################

####################################################################
res <- run_sc_sequencing(tumour_bams=bams,
                         fasta=fasta,
                         allchr=paste0("",c(1:22,"X","Y")), ## might need a "chr" instead of "" if hg38
                         sex=rep("male",length(bams)),
                         chrstring_bam="",  ## might need a "chr" instead of "" if hg38
                         purs = seq(0.1, 1, 0.01) , ## purity grid values
                         ploidies = seq(1.7,5, 0.01), ## average ploidy grid values
                         maxtumourpsi=5, ##maximum tumour ploidy
                         binsize=500000, ## bin size - reduce if enough sequencing reads (look at dpb (depth per bin) value in plots can go down to 100bp or even lower)
                         build="hg19", ## either hg19 or hg38 so far
                         projectname="name_of_my_run",
                         MC.CORES=7, ##number of cores available
                         multipcf=FALSE) ##use multipcf for multi-track segmentation if multi-sample sequencing
####################################################################
save(res,file="ASCAT.sc.results.Rda") ## save results for reuse later on
####################################################################
```

Hopefully most of it is self-explanatory.  In the object "res", which is a list with all data/results, the element named "summary" will contain purity and ploidy values across your bams. Please use the "refitted" values (these are automatically refitted to better match the space of high-quality profiles, which relies on the xgboost library). Please let me know how it goes.

**Comment by lbeltrame** [comment]
Thanks! I will try to give it a go in the next few days/weeks (I'm going on holiday at the end of this week) and I'll let you know.

**Comment by lbeltrame** [comment]
I was actually able to finally run this and I have a couple questions on the output:

- Does `allProfiles` contain the relative and absolute copy number per segment in the results for the identified purity/ploidy combination?
- If so, do you think it would be a worthwhile addition to also add the number of bins per segment? That would make the output compatible with some ancient software like GISTIC.

**Comment by galder-max** [comment]
Hi Ibeltrame, yes, indeed! 

The current allProfiles (you will have to reinstall the package) will contain the following columns:

chromosome
start
end
num.mark => number of bins
total_copy_number => fitted integer copy number (rounded)
total_copy_number_logr => non-rounded fitted copy number
logr => logr = log2(counts)/ average(log2(counts)) corrected for GC content
logr.sd => stantard deviation of the logr within the segment

I will try and add this info -- and more-- soon. Currently, adjacent segments with the same rounded copy number are not merged; but this should come as an additional output soon.

**Comment by pawelqs** [comment]
Hi, 
I used the code above to run ASCAT.sc on my shallow WGS data and many fits are pretty good, but some are very inaccurrate like the one below. How can improve the fit? I see refitProfile() function, but it lacks any documentation.
Best,
Paweł
![image](https://user-images.githubusercontent.com/38688203/222427896-ccc23313-823d-4d84-8dc1-bc99bb96a79f.png)

**Comment by galder-max** [comment]
Hi @pawelqs, sorry for the super late reply! 

There are now wiki pages for ASCAT.sc, one of which explains how to refit the profiles (https://github.com/VanLoo-lab/ASCAT.sc/wiki/manual_refitting). 

You will have to update ASCAT.sc to the newest version to have access to the refitting functions - I would also recommend rerunning on your samples, which will now write a res.Rda object to disk, which can be reused for refitting and future tuning.

Are your scWGS single cells or bulk?  If you have diploid samples, you might also want to provide them to the function to allow to further correct the logR. 

Hope this helps and apologies again for the delay in replying - I recommend creating a new issue in the future, as it helps better keeping track.

**Comment by galder-max** [comment]
Closing issue as documentation in wiki pages now covering these questions.
