### ISSUE TITLE
Enhancement request: provide per-bin fitted absolute CN

### ISSUE THREAD

**Issue by lbeltrame** [VanLoo-lab/ASCAT.sc#12]
This should be retrieved from the solutions. The use case for such a table is to group bins per copy number value (in this case, since some bins will not be included, this will create non-consecutive segments, unlike proper segments) to perform additional analyses (e.g. to identify breakpoints). 

I took a look at the outputs from a sWGS analysis but I couldn't find anything of the sort at a first glance, hence I'm opening this issue.

For example of other software doing this, ichorCNA provides such a measure in its output tables.

**Comment by galder-max** [comment]
Hi @lbeltrame 
sorry for the massive delay. 
I am not sure to understand exactly. This seems trivial to extract from the current outputs, since we added the number of bins per segment at your request (which is then a run-length encoded version of what you are describing)?

**Comment by lbeltrame** [comment]
That might be as you say. Sorry for the delay myself, I needed to look into it but I couldn't find the time yet.
