### ISSUE TITLE
The bin size can not be changed

### ISSUE THREAD

**Issue by beginner984** [VanLoo-lab/ASCAT.sc#22]
Hi

I tried bin size of 1k but I noticed bin size has a minimum

```
null device 
          1 
PNG file saved at: fastq/preprocessing/recalibrated//COX.png 
[1] "checking arguments"
[1] "## load Bins for Genome Build: hg38"
[1] "Current minimum bin size is 30000 - resetting to 30000"
[1] "## calculate Target Bin size"
[1] "## get Tracks from Tumour bams"
[1] "## smooth Tracks"
[1] "   ## correct for GC content"
[1] "   ## segment Tracks"
[1] "## fit Purity/Ploidy"
Solution found.
[1] "## get Fitted CNA Profiles"
[1] "## compile Results"
[1] "## predict Refit"
[1] "## print Results"
```
This is the output 

![COXP_LM recal bam](https://github.com/user-attachments/assets/ce1728ae-a413-4316-b847-06a62470a510)

So, this means I can not decrease bin size more as my data has `24x` ?

**Comment by galder-max** [comment]
Indeed, the current minimum bin size is 30000 (as mentioned in my previous message and printed by the function [1] "Current minimum bin size is 30000 - resetting to 30000"). It could in theory be decreased further but not with the current code, and is already very low for typical shallow-coverage experiments, where bin sizes of up to 1Mb are used.

**Comment by beginner984** [comment]
Thanks a lot

I just rum the same code on the same sample (WGS, tumour only) with `7x` and this is the results 

![COXP_LM recal bam](https://github.com/user-attachments/assets/9c2128b1-da29-4ae2-ab0d-56615ba91b5a)

[1] "checking arguments"
[1] "## load Bins for Genome Build: hg38"
[1] "Current minimum bin size is 30000 - resetting to 30000"
[1] "## calculate Target Bin size"
[1] "## get Tracks from Tumour bams"
[1] "## smooth Tracks"
[1] "   ## correct for GC content"
[1] "   ## segment Tracks"
[1] "## fit Purity/Ploidy"
Solution found.
[1] "## get Fitted CNA Profiles"
[1] "## compile Results"
[1] "## predict Refit"
[1] "## print Results"

**Comment by galder-max** [comment]
The results are the same as previously. 
Downsampling to lower depth will not help increase the resolution: the bin size is still reset to 30kb and you will loose power by reducing the number of reads in each bin. 
From these figures and the ASCAT run, there is clearly no gain on chr20 in that sample - which looks pretty diploid and "normal" for a cell line.

**Comment by beginner984** [comment]
Thanks a lot for bearing with users 

Actually trying `7x` was not exactly downsampling to lower depth rather last year we sequenced samples with `7x` and this year we re-sequenced to `24x`.

By the way, I tried with another sample from last year sequencing (`7x`) in which SNParrays has shown duplication in `chromosome 20` as well.

This is the results 
![RUMA_LM2 recal bam](https://github.com/user-attachments/assets/e5d529f7-43cd-4b72-adf9-e61c9347627f)
[RUMA_LM2.recal.bam_RUMA_refitted.ASCAT.scprofile.txt](https://github.com/user-attachments/files/17504121/RUMA_LM2.recal.bam_RUMA_refitted.ASCAT.scprofile.txt)

**Comment by beginner984** [comment]
Hi

Cell line here taken from a different patient (`7x`), we had three cancer patient

I used `bin size 30k` which returns this
![RUMA_LM2 recal bam](https://github.com/user-attachments/assets/750c5130-6af1-4e5e-81f0-9ef83a2510e6)

I used `bin size 40k` which returns this

![RUMA_LM2 recal bam](https://github.com/user-attachments/assets/31a9d177-d30b-442e-938a-622a1313fe3b)

I `used bin size 50k` which returns this

![RUMA_LM2 recal bam](https://github.com/user-attachments/assets/285f8d69-8e45-4111-a11e-4d77ac6d8886)

Please, in your opinion, I should trust which bin size more?

Also that ploidy finder function you kindly suggested can not be run

```
> ASCAT.sc::run_PloidyModifier()

Listening on http://127.0.0.1:4889
Couldn't get a file descriptor referring to the console
```

Let me thank you once more
