### ISSUE TITLE
Enhancement request for sWGS: provide number of bins per segment in output files / tables

### ISSUE THREAD

**Issue by lbeltrame** [VanLoo-lab/ASCAT.sc#4]
While this can be extracted from the result object, it saves time to have the number of bins directly in the output. This allows compatibility with ancient software like GISTIC.

**Comment by galder-max** [comment]
Thanks for the suggestion! A column with the number of bins/markers has been added to the output profiles.

**Comment by lbeltrame** [comment]
Oh, you were fast! I was just about to paste the code I had in mind to do that...
