### ISSUE TITLE
Error in lCTS[[1]] : subscript out of bounds

### ISSUE THREAD

**Issue by Urja25** [VanLoo-lab/ASCAT.sc#8]
Hi,

I am trying to run this tool on extremely low coverage single-cell whole genome data with the following code:
res <- run_sc_sequencing(tumour_bams=bams, ##vector of full paths to your bam files
                         sex=rep("female",length(bams)), ##sex for each bam
                         allchr=paste0("chr",c(1:22,"X", "Y")),
                         binsize=500000, ##bin size - reduce at higher depths
                         purs = seq(.999, 1, 0.001),##value of purity
                         chrstring_bam="chr",
                         ploidies = seq(1.7,5, 0.01), ##value of ploidy
                         maxtumourpsi=5, ## maximum tumour poidy considered
                         build="hg38", ##build, either hg19 or hg38
                         MC.CORES=4,##how many cores to use
                         outdir="/home/ASCAT_results",
                         projectname="LFS02CP",
                         multipcf=T)

I get the following error:
Error in lCTS[[1]] : subscript out of bounds
In addition: Warning messages:
1: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘copynumber’
2: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘copynumber’
Timing stopped at: 0.003 0.002 0.003

Can you please help me resolve this?

**Comment by galder-max** [comment]
Dear Urja25,
Could you please try and install the package "copynumber" and try again? It is needed if multipcf=T

**Comment by Urja25** [comment]
Hi @galder-max,

I did that and re-ran the script to get the same error without the warning:
Loading required package: future
[1] "checking arguments"
[1] "## load Bins for Genome Build: hg38"
[1] "## calculate Target Bin size"
[1] "## get Tracks from Tumour bams"
[1] "## calculate Multipcf - multi-sample mode - do not use if samples from different tumours"
[1] "Smoothing all tracks"

Error in lCTS[[1]] : subscript out of bounds
Calls: run_sc_sequencing -> system.time -> getLSegs.multipcf
Timing stopped at: 0.001 0 0.001
Execution halted

**Comment by galder-max** [comment]
Thanks, @Urja25! 
It is difficult to know why this happens in your case. 
Could you now check a couple things please:
1) verify your genome build, contig names (with or without "chr") and paths to bam files are as expected.
2) run with multipcf=FALSE and see if it runs through - maybe try a single bam not to have to wait too long
